services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myapp-dev-1
    restart: always
    env_file:
      - .env.dev
    environment:
      - APP_NAME=app1
    ports:
      - "${PORT}:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - sr-app_task-network
  nginx:
    image: nginx:latest
    container_name: nginx-dev
    env_file:
      - .env.dev
    ports:
      - "8080:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app1
    networks:
      - sr-app_task-network
networks:
  sr-app_task-network:
    external: true
